[build]
  command = "npm ci && npm run build"
  publish = "dist/client"
  functions = "dist/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob: https://*.supabase.co https://*.netlify.app https://*.google.com https://*.googleapis.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' 'wasm-unsafe-eval' https://*.supabase.co https://*.netlify.app https://*.google.com https://*.googleapis.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' data: https://fonts.gstatic.com;
      img-src 'self' data: blob: https://*.supabase.co https://*.netlify.app https://*.google.com https://*.googleapis.com;
      connect-src 'self' data: blob: https://*.supabase.co https://*.netlify.app https://api-inference.huggingface.co https://*.google.com https://*.googleapis.com;
      frame-src 'self' https://*.supabase.co https://*.netlify.app https://*.google.com;
      worker-src 'self' blob: 'unsafe-eval';
      trusted-types 'none';
      require-trusted-types-for 'script';
      """
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"

[build.environment]
  NODE_VERSION = "18"
  SUPABASE_URL = "https://xocawdbmzzukfwfvawwm.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvY2F3ZGJtenp1a2Z3ZnZhd3dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTY5MDUsImV4cCI6MjA2MDU3MjkwNX0.gtPDCOK5Zv1U_ihbTDprv_-i7ULsJV4JLKba9c6tGZQ"
  VITE_SUPABASE_URL = "https://xocawdbmzzukfwfvawwm.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvY2F3ZGJtenp1a2Z3ZnZhd3dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTY5MDUsImV4cCI6MjA2MDU3MjkwNX0.gtPDCOK5Zv1U_ihbTDprv_-i7ULsJV4JLKba9c6tGZQ"
  VITE_API_URL = "/.netlify/functions"
  HUGGINGFACE_API_KEY = "${HUGGINGFACE_API_KEY}"
  VITE_SITE_URL = "https://dynamic-licorice-006a2f.netlify.app"

[functions]
  included_files = [".env"]
  node_bundler = "esbuild"
  external_node_modules = ["@babel/preset-typescript", "lightningcss"]

[context.production]
  environment = { NODE_VERSION = "18", NODE_ENV = "production" } 