[build]
  command = "npm run build"
  publish = "dist/client"
  functions = "dist/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[functions]
  included_files = [".env"]

[context.production.environment]
  NODE_ENV = "production" 